name: PII/Secrets scan
on:
  pull_request:
    paths:
      - "**/*"
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jpetrucciani/rg-action@v2
        with:
          args: |
            -n --hidden --glob=!node_modules --glob=!.git --glob=!AP-Private --glob=!screenshots --glob=!student-submissions/**/assets --glob=!scripts/pii_scan.sh \
            -e '[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}' \
            -e '(?i)(\+?\d[ )-]?){10,}' \
            -e '(?i)\bjoin\s+codes?\s*:\s*[A-Z0-9-]{6,}\b' \
            -e '(?i)\bAP[ _-]?ID\s*:\s*\d{6,10}\b'