name: Weekly submission check

on:
  pull_request:
    paths:
      - "**/*"

jobs:
  weekly_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate submission format
        run: bash scripts/validate_submission.sh
      - name: Audit week docs
        run: bash scripts/audit_weeks.sh